version: '2'
services:
  tm:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '5000:8000'
  db:
    build:
      context: ./devops/docker/postgis
      dockerfile: Dockerfile
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - '5435:5432'
volumes:
  db-data:
    external:
      name: tm-db-data