"""empty message

Revision ID: cc755fe88ce3
Revises: 16d42da99601
Create Date: 2018-11-23 12:20:41.090216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc755fe88ce3'
down_revision = '16d42da99601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.create_index('textsearch_idx', 'project_info', ['text_searchable'], unique=False)
    op.drop_index('idx_project_info composite', table_name='project_info')
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_project_info composite', 'project_info', ['locale', 'project_id'], unique=False)
    op.drop_index('textsearch_idx', table_name='project_info')
    op.drop_index('idx_project_info composite', table_name='project_info')
    # ### end Alembic commands ###
